import React from 'react';
import { View, ScrollView, StyleSheet, SafeAreaView, Pressable, RefreshControl } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { useTheme } from '../../../lib/theme';
import { useAuthStore } from '../../../stores/authStore';
import { supabase } from '../../../lib/supabase';
import { ThemedText, Card, Badge, EmptyState, ErrorState, SectionHeader } from '../../../components/ui';
import { Spacing } from '../../../constants/Typography';
import { ScreenHeader } from '../../../components/ui/ScreenHeader';
import { Colors } from '../../../constants/Colors';
import { Ionicons } from '@expo/vector-icons';

function useParentFees(parentId: string | null, schoolId: string) {
  return useQuery({
    queryKey: ['parent-fees', parentId, schoolId],
    enabled: !!parentId && !!schoolId,
    staleTime: 1000 * 60 * 2,
    queryFn: async () => {
      // Get linked students
      const { data: links } = await supabase
        .from('student_parent_links')
        .select('student_id, students(id, full_name, student_number)')
        .eq('parent_id', parentId!)
        .eq('school_id', schoolId);
      
      const students = (links ?? []).map((l: any) => l.students);
      if (students.length === 0) return { students: [], invoices: [] };

      const studentIds = students.map((s: any) => s.id);

      // Get active semester
      const { data: sem } = await supabase
        .from('semesters')
        .select('id, name')
        .eq('school_id', schoolId)
        .eq('is_active', true)
        .single();

      // Get invoices
      const { data: invoices } = await supabase
        .from('invoices')
        .select('*')
        .in('student_id', studentIds)
        .eq('semester_id', sem?.id ?? '')
        .order('created_at', { ascending: false });

      // Get finance records (legacy)
      const { data: financeRecords } = await supabase
        .from('finance_records')
        .select('*')
        .in('student_id', studentIds)
        .eq('semester_id', sem?.id ?? '');

      return {
        semester: sem,
        students,
        invoices: invoices ?? [],
        financeRecords: financeRecords ?? [],
      };
    },
  });
}

export default function ParentFees() {
  const { colors } = useTheme();
  const { user } = useAuthStore();
  const parentId = user?.staffId ?? null;
  const schoolId = user?.schoolId ?? '';

  const { data, isLoading, isError, refetch, isRefetching } = useParentFees(parentId, schoolId);

  const totalOutstanding = (data?.invoices ?? [])
    .filter((inv: any) => inv.status !== 'paid')
    .reduce((sum: number, inv: any) => sum + (inv.balance ?? 0), 0);

  if (isError) {
    return (
      <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
        <ErrorState title="Could not load fees" description="Try again." onRetry={refetch} />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
      <ScreenHeader title="School Fees" showBack />

      <ScrollView
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} tintColor={colors.brand.primary} />}
      >
        {/* Summary */}
        <Card style={{ margin: Spacing.screen, padding: Spacing.lg }}>
          <ThemedText variant="label" color="muted">TOTAL OUTSTANDING</ThemedText>
          <ThemedText variant="h1" style={{ color: totalOutstanding > 0 ? Colors.semantic.error : Colors.semantic.success }}>
            {totalOutstanding.toLocaleString?.() ?? totalOutstanding}
          </ThemedText>
          <ThemedText variant="caption" color="muted">{data?.semester?.name ?? 'Current Term'}</ThemedText>
        </Card>

        {/* Invoices per student */}
        <SectionHeader title="Invoices" />
        {isLoading ? (
          <Card style={{ margin: Spacing.screen, padding: Spacing.lg }}><ThemedText>Loading...</ThemedText></Card>
        ) : data?.invoices.length === 0 ? (
          <EmptyState title="No invoices" description="Invoices appear once generated by Finance." icon="document-text-outline" />
        ) : (
          data?.students.map((student: any) => {
            const studentInvoices = (data?.invoices ?? []).filter((inv: any) => inv.student_id === student.id);
            if (studentInvoices.length === 0) return null;

            return (
              <View key={student.id} style={{ marginHorizontal: Spacing.screen, marginBottom: Spacing.lg }}>
                <ThemedText variant="body" style={{ fontWeight: '600', marginBottom: Spacing.sm }}>
                  {student.full_name}
                </ThemedText>
                {studentInvoices.map((inv: any) => (
                  <Card key={inv.id} style={{ marginBottom: Spacing.sm, padding: Spacing.md }}>
                    <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
                      <View>
                        <ThemedText style={{ fontWeight: '600' }}>{inv.invoice_number}</ThemedText>
                        <ThemedText variant="caption" color="muted">Due: {inv.due_date ?? '—'}</ThemedText>
                      </View>
                      <View style={{ alignItems: 'flex-end' }}>
                        <ThemedText style={{ fontWeight: '700' }}>{inv.total_amount?.toLocaleString?.() ?? inv.total_amount}</ThemedText>
                        <Badge
                          label={inv.status}
                          preset={inv.status === 'paid' ? 'success' : inv.status === 'partial' ? 'warning' : 'error'}
                          variant="tonal"
                        />
                      </View>
                    </View>
                    {inv.balance > 0 && (
                      <View style={{ marginTop: Spacing.sm, paddingTop: Spacing.sm, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }}>
                        <ThemedText variant="caption" color="muted">
                          Balance: {inv.balance.toLocaleString?.() ?? inv.balance}
                        </ThemedText>
                      </View>
                    )}
                    {inv.pdf_url && (
                      <Pressable style={{ marginTop: Spacing.sm, flexDirection: 'row', alignItems: 'center' }}>
                        <Ionicons name="download-outline" size={16} color={colors.brand.primary} />
                        <ThemedText style={{ color: colors.brand.primary, marginLeft: Spacing.xs }}>Download PDF</ThemedText>
                      </Pressable>
                    )}
                  </Card>
                ))}
              </View>
            );
          })
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
});
